### ISSUE TITLE
Plugin Parsing buildkite-agent as a directory instead of command

### ISSUE THREAD

**Issue by BintLopez** [bugcrowd/test-summary-buildkite-plugin#23]
I'm experiencing errors trying to use this plugin.

**Error:**  `Errno::ENOENT: No such file or directory - buildkite-agent`

**Full Stack Trace**
```
Running plugin github.com/bugcrowd/test-summary-buildkite-plugin#v1.4.0 command hook | 7s
-- | --
  | $ /buildkite/plugins/github-com-bugcrowd-test-summary-buildkite-plugin-v1-4-0/hooks/command
  | Found tag v1.4.0, pulling from docker hub
  | v1.4.0: Pulling from tessereth/test-summary-buildkite-plugin
  | ff3a5c916c92: Already exists
  | 8e2da6035957: Pull complete
  | 42e99ed6de92: Pull complete
  | 70c638bbd0d9: Pull complete
  | 6707ebcdc256: Pull complete
  | 72dd2f0132d6: Pull complete
  | 06c7a1fb7b48: Pull complete
  | 31374a9fe479: Pull complete
  | 1026ef473bca: Pull complete
  | Digest: sha256:242107f59f9c9a2a29e6d9b70892548adc513f91eb396c10b79e1b0790d4821a
  | Status: Downloaded newer image for tessereth/test-summary-buildkite-plugin:v1.4.0
  | $ buildkite-agent artifact download junit_rspec_report_*.xml tmp/test-summary
  | Errno::ENOENT: No such file or directory - buildkite-agent
  |  
  | /usr/src/app/lib/test_summary_buildkite_plugin/agent.rb:21:in `popen'
  | /usr/src/app/lib/test_summary_buildkite_plugin/agent.rb:21:in `run'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:40:in `files'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/formatter.rb:22:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:49:in `input_markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `block in markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `map'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:17:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/runner.rb:19:in `run'
  | /usr/src/app/lib/test_summary_buildkite_plugin.rb:19:in `run'
  | ./bin/run:10:in `<main>'
  | No errors found! 🎉
```

This is how I've set up my pipeline:
```
 - name: 'Test'
    label: tests
    command: '.buildkite/test'
    artifact_paths:
      - "junit_rspec_report_*.xml"

  - wait: ~
    continue_on_failure: true

  - name: ':scroll: Annotate'
    plugins:
      bugcrowd/test-summary#v1.4.0:
        inputs:
          - label: tests
            artifact_path: "junit_rspec_report_*.xml"
            type: junit
```

Not sure if I'm missing something important in my set up or if this is a broader issue. Please let me know what other info I can provide to help debug.
