### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by brett-anderson** [bugcrowd/test-summary-buildkite-plugin#69]
Hello, we've recently migrated to an ARM stack, and it's looking like our results step is failing:

```
# # Compile junit tests
  - label: ":coverage: Results"
    agents:
      queue: east-2-testrunner-v1
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: ":ruby: Rspec"
              artifact_path: "artifacts/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary
```

This is the output from buildkite:

<img width="1235" alt="Screen Shot 2021-04-19 at 3 59 23 PM" src="https://user-images.githubusercontent.com/3645267/115303080-c58c4480-a128-11eb-88b4-0aa6130fab47.png">

Wondering what it would take to get this running on ARM?
